---
# Swarm config vars
jenkins_agent_master_port: 8080
jenkins_agent_username: admin
jenkins_agent_password: "{{ lookup('password', '../credentials/{{ inventory_hostname }}/jenkins-agent/agent-password.txt') }}"
jenkins_agent_name: "{{ inventory_hostname }}"
jenkins_agent_num_executors: "{{ ansible_processor_cores|default(1)*2 }}"
jenkins_agent_retries: 5
jenkins_agent_labels: "{{ (ansible_os_family|lower() == 'windows')|ternary('windows', 'linux') }}"
jenkins_agent_labels_file: "{{ jenkins_swarm_path }}/labels.swarm"
jenkins_agent_log_file: "{{ jenkins_swarm_path }}/swarm.log"
jenkins_agent_additional_args:
  - "-deleteExistingClients"
  - "-disableClientsUniqueId"


jenkins_home: /var/jenkins
jenkins_slave_name: jenkins_slave
jenkins_master_hostname: 192.128.20.14
jenkins_master_port: 8080
jenkins_master_username: admin
jenkins_master_password: admin


jenkins_user: jenkins
jenkins_group: jenkins
jenkins_log_dir: /opt/elasticsearch/log

# Swarm client url building
jenkins_swarm_client_version: 3.23
# jenkins_plugins_url: https://repo.jenkins-ci.org
# jenkins_plugins_repo_path: "releases/org/jenkins-ci/plugins/swarm-client/{{ jenkins_swarm_client_version }}"
# jenkins_swarm_client_jar: "swarm-client-{{ jenkins_swarm_client_version }}.jar"
# jenkins_swarm_download_url: "{{ jenkins_plugins_url }}/{{ jenkins_plugins_repo_path }}/{{ jenkins_swarm_client_jar }}"
jenkins_swarm_download_url: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/{{ jenkins_swarm_client_version }}/swarm-client-{{ jenkins_swarm_client_version }}.jar

# Linux Vars
jenkins_swarm_path: /var/lib/jenkins
jenkins_swarm_config_path: /etc/jenkins
jenkins_swarm_task_name: Jenkins Swarm Client
jenkins_swarm_systemd_path: /lib/systemd/system
jenkins_swarm_service_name: swarm-client

# Windows Vars
version: 2.0.3
jenkins_swarm_client_wrapper_version: 2.0.3
jenkins_swarm_wrapper_download_url: "{{ jenkins_plugins_url}}/releases/com/sun/winsw/winsw/{{ jenkins_swarm_client_wrapper_version }}/winsw-{{jenkins_swarm_client_wrapper_version}}-bin.exe"
win_java_version: 8.0.144
win_base_jenkins_path: "C:\\jenkins"
win_swarm_client_jar_path: "{{ win_base_jenkins_path }}\\{{ jenkins_swarm_client_jar }}"
win_swarm_client_wrapper_path: "{{ win_base_jenkins_path }}\\{{ jenkins_swarm_client_jar|replace('.jar', '.exe') }}"
win_swarm_client_wrapper_config_path: "{{ win_base_jenkins_path }}\\{{ jenkins_swarm_client_jar|replace('.jar', '.xml') }}"
