---
scenario:
  name: default
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: jenkins-master
    box: bento/centos-8.2
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 8080, host: 8080"
      - "vm.network 'forwarded_port', guest: 9999, host: 9999"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
      - auto_config: false
        network_name: private_network
        type: dhcp
      - auto_config: true
        ip: 192.128.20.14
        network_name: private_network
        type: static
  - name: jenkins-slave
    box: bento/centos-8.2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
      - auto_config: false
        network_name: private_network
        type: dhcp
      - auto_config: true
        ip: 192.128.20.15
        network_name: private_network
        type: static
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
