---
dependency:
  name: galaxy
# driver:
#   name: docker
platforms:
  # - name: jenkins-master-rhel8
  #   image: registry.access.redhat.com/ubi8/ubi-init
  #   pre_build_image: true
  #   published_ports:
  #     - "8080:8080"
  #     - "9999:9999"
  #   # privileged: true
  # - name: jenkins-slave-rhel8
  #   image: registry.access.redhat.com/ubi8/ubi-init
  #   pre_build_image: true
    # privileged: true
  - name: jenkins-master-centos
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    published_ports:
      - "8080:8080"
      - "9999:9999"
  - name: jenkins-slave-centos
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    command: /sbin/init
    privileged: true
    capabilities:
      - SYS_ADMIN
    # volumes:
      # - /var/run/docker.sock:/var/run/docker.sock:rw
      # - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # - /usr/local/bin/docker:/usr/bin/docker

    # command: /sbin/init
    # tmpfs:
    #   - /run
    #   - /tmp
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # pre_build_image: true
    # privileged: true
    # capabilities:
    #   - SYS_ADMIN
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
