---
- hosts: jenkins-master
  roles:
    - {role: java, become: true }
    - {role: jenkins-master, become: true }
- hosts: jenkins-slave
  roles:
    - {role: java, become: true }
    - {role: jenkins-slave, become: true }
    - {role: docker, become: true }
