---
- hosts: jenkins-master
  roles:
    - {role: java, become: true, become_method: su, become_user: root}
    - {role: jenkins-master, become: true, become_method: su, become_user: root}
- hosts: jenkins-slave
  roles:
    - {role: java, become: true, become_method: su, become_user: root}
    - {role: jenkins-slave, become: true, become_method: su, become_user: root}
